// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package spanner

import (
	"github.com/conduitio/conduit-commons/config"
)

const ()

func (DestinationConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{}
}
