// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package spanner

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	SourceConfigDatabase = "database"
	SourceConfigEndpoint = "endpoint"
)

func (SourceConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		SourceConfigDatabase: {
			Default:     "",
			Description: "Database is the name of the database to use. A valid database name has the\nform projects/PROJECT_ID/instances/INSTANCE_ID/databases/DATABASE_ID",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		SourceConfigEndpoint: {
			Default:     "",
			Description: "Endpoint is the URL for endpoint override - testing/dry-run only",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
